-- =============================================
-- DISABLE RLS ON ALL TABLES
-- Para desarrollo y pruebas del proyecto
-- =============================================

ALTER TABLE roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE cursos DISABLE ROW LEVEL SECURITY;
ALTER TABLE inscripciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE unidades DISABLE ROW LEVEL SECURITY;
ALTER TABLE materiales DISABLE ROW LEVEL SECURITY;
ALTER TABLE tareas DISABLE ROW LEVEL SECURITY;
ALTER TABLE entregas DISABLE ROW LEVEL SECURITY;
ALTER TABLE cuestionarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE preguntas DISABLE ROW LEVEL SECURITY;
ALTER TABLE opciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE respuestas_estudiante DISABLE ROW LEVEL SECURITY;
ALTER TABLE calificaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE foros DISABLE ROW LEVEL SECURITY;
ALTER TABLE mensajes_foro DISABLE ROW LEVEL SECURITY;
